#!/bin/bash
# Run UOAM in UOR Wine container
scriptname=`basename "$0"`
source uor-install.sh.conf

echo UOR Wine directory is $uordir
echo Wine Prefix  is $WINEPREFIX
echo Wine Architecture is $WINEARCH
echo Wine Debug is $WINEDEBUG

"$uordir/uorwine" "$uoampath/uoam_auto.exe" -q &
